#
# Update the conda installation
# conda update -n base -c defaults conda
#
# Install flywheel
# conda env create -f flywheel/requirements.yaml
#

name: flywheel
channels:
 - defaults
dependencies:
 - python=3.10
 - pip
 - pip:
    - flywheel-gear-toolkit
    - flywheel-sdk
    - globre
    - numpy
    - pandas
    - pyjq
    - pytz
    - requests
    - tzlocal
