#!/bin/bash

export FLYWHEEL=${FLYWHEEL:=/flywheel/v0}
export PATH=${FLYWHEEL}:/usr/local/flywheel/bin:$PATH
export PYTHONPATH=/usr/local/pyjq:/usr/local/flywheel/lib

export FLYWHEEL_INPUTDIR="${FLYWHEEL}/input"
export FLYWHEEL_OUTPUTDIR="${FLYWHEEL}/output"

while read line
do
	f=$(realpath "${FLYWHEEL_INPUTDIR}/${line}")
	toNifti -v -o "$FLYWHEEL_OUTPUTDIR" "$f"
done < <( ls "$FLYWHEEL_INPUTDIR" | grep -E '(.nii|.nii.gz|.dcm|.dicom|.dicom.zip|dcm.zip)$' )
