#!/bin/bash -x

InImg="$(ls input/input-file/* | head -n 1)"
Basename=$(basename "$InImg" | sed 's/.nii.gz//')
OutImg="output/${Basename}-OutSeg.nii.gz"

python ./segmentation.py --inImg "$InImg" --outSeg "$OutImg"
