#!/bin/bash

CmdName=$(basename "$0")

Syntax="${CmdName} [-a][-l][-n][-v][-p ProjectInfoJsonFile]"

ProjectInfoPath='.ProjectFunding'
TmpDir="${TMPDIR:=/tmp}"

InternalGroupJson='[
        "camris"
      , "fw-support"
      , "holder"
      , "nncadim"
      , "techdev"
]'
InternalGroupRegex=$(echo "$InternalGroupJson" | jq -j 'join("|")')

JqFindProjectFundingInfo='
      (.group + "/" + .label) as $GroupProjectPath
    | (if ($GroupProjectPath | test("^('"$InternalGroupRegex"')/")) then
                   "Free"
               else
                   "Paid"
               end) as $GroupType
    | .info.ProjectFunding
	    | .accountNumber as $AccountNumber
	    | .businessAdministrator.name as $BaName
	    | .businessAdministrator.email as $BaEmail
            | (if (.PIs) then 
                 .PIs | join(":")
                else
	         ""
	        end) as $PiNamesAndEmails
             | (.iLabServiceRequestNumber) as $ServiceRequestNumber
             | [ $GroupProjectPath, $GroupType, $PiNamesAndEmails, $BaName, $BaEmail, $AccountNumber, $ServiceRequestNumber ]
             | @csv
'


while getopts "alnp:v" arg
do
    case "$arg" in
	a|l|n|p|v)
	    eval "opt_${arg}='${OPTARG:=1}'"
	    ;;
    esac
done

shift $(("$OPTIND" - 1))

if [ -n "$opt_p" ]
then
    DeleteProjectInfoJsonFile=false
    ProjectInfoJsonFile="$opt_p"
else
    DeleteProjectInfoJsonFile=true
    ProjectInfoJsonFile=$(mktemp "${TmpDir}/${CmdName}-XXXXXX")
fi

[ -n "$opt_l" ] && DeleteProjectInfoJsonFile=false


if [ ! -s "$ProjectInfoJsonFile" ]
then
   fwfind --exhaustive -1  -p > "$ProjectInfoJsonFile"
fi

# Print all project funding info
if [ -n "$opt_a" ]
then
    jq -r "$JqFindProjectFundingInfo" "$ProjectInfoJsonFile"
    exit 0
fi


ProjectsMissingPis=$(jq -r "$JqFindProjectFundingInfo" "$ProjectInfoJsonFile" | csvcut -c 1-3 | grep -v ',Free,' | grep ',$' | sort)
if [ -n "$ProjectsMissingPis" ]
then
    echo "Projects Missing PIs"
    echo
    echo "$ProjectsMissingPis"
    echo
fi

ProjectsMissingServiceRequestNumbers=$(jq -r "$JqFindProjectFundingInfo" "$ProjectInfoJsonFile"| csvcut -c 1-6 | grep -v ',Free,' | grep -v ',InternalBenNumber,' | grep ',$' | sort)
if [ -n "$ProjectsMissingServiceRequestNumbers" ]
then
    echo "Projects Missing Service Request Numbers"
    echo
    echo "$ProjectsMissingServiceRequestNumbers"
    echo
fi

[ "$DeleteProjectInfoJsonFile" = 'true' ] && rm "$ProjectInfoJsonFile"
