#!/bin/bash

CmdName=$(basename "$0")

Rhost=bscsub.pmacs.upenn.edu
RReportDir=/project/bsc/Billing/Reports
RILabChargesDir=/project/bsc/Billing/iLabCharges
RCalculateCmd=/project/bsc/Billing/bin/calculateBscStorageCharges

function findReportFile {
    local File="$1"
    local Date="$2"
    local YearMonth="$3"
    local NestYearMonth="$4"

    Dirs=( ~/Work/flywheel/GCPBilling/${YearMonth} ~/Downloads )
    for d in "${Dirs[@]}"
    do
	FileName=$(realpath "${d}/${Date}-${File}")
	[ -e "$FileName" ] && break

	FileName=$(realpath "${d}/${File}")
	[ -e "$FileName" ] && break
    done

    if [ -n "$FileName" ] && [ -e "$FileName" ]
    then
	
	ReportDate=$(dos2unix < "$FileName" | head -n 1 | awk '{print $NF}' )
	if ( [[ "$ReportDate" > "$Date" ]] || [ "$ReportDate" = "$Date" ] ) && ( [[ "$ReportDate" < "$NextYearMonth" ]] || [[ "$ReportDate" -eq "$NextYearMonth" ]] )
	then
	    echo "$FileName"
	    return
	else
            echo "$report date outside specified Date Range $Date - $ReportDate - $NextYearMonth" 1>&2
	fi
    fi
}

function ssh2bscsub {
    local RCmd=( "$@" )

    local Cmd=( cat )

    [ "$(hostname -s)" == "fritz" ] && Cmd=( ssh vpn-uphs ssh chead ssh bscsub "${RCmd[@]}" )
    [ "$(hostname -s)" == "chead" ] && Cmd=( ssh bscsub "${RCmd[@]}" )

    echo "${Cmd[@]}"
}

# *** should be able to change report locations, both local and remote
# *** should be able to do a quiet mode
# *** add -n -v and change echos out

Day=$(date +%d)
Month=$(date +%m)
Year=$(date +%Y)

while getopts d:m:y: arg
do
	case "$arg" in
	     d|m|y)
		eval "opt_${arg}=${OPTARG:=1}"
		;;
	esac
done

shift $(($OPTIND - 1))

[ -n "$opt_d" ] && Day="$opt_d"
[ -n "$opt_m" ] && Month="$opt_m"
[ -n "$opt_y" ] && Year="$opt_y"

Date="${Year}-${Month}-${Day}"
YearMonth="${Year}-${Month}"
NextYearMonth=$(date -d "${Date} + month" +"%Y-%m-01")

RHost=$(ssh2bscsub hostname -s | bash)
if [ "$RHost" != "bscsub1" ]
then
    echo "${CmdName} : Can not get to bscsub1" 1>&2
    exit 2
fi


LPmacsUserReportFile=$(findReportFile userreport.txt "$Date" "$YearMonth" "$NextYearMonth")
if [ -z "$LPmacsUserReportFile" ]
then
    echo "${CmdName} : Missing UserReportFile" 1>&2
    exit
fi
RPmacsUserReportFile="${RReportDir}/${Date}-userreport.txt"
echo "cat $LPmacsUserReportFile | $(ssh2bscsub tee $RPmacsUserReportFile)"
   
LPmacsProjectReportFile=$(findReportFile projectreport.txt "$Date" "$YearMonth" "$NextYearMonth")
if [ -z "$LPmacsProjectReportFile" ]
then
    echo "${CmdName} : Missing ProjectReportFile" 1>&2
    exit
fi
RPmacsProjectReportFile="${RReportDir}/${Date}-projectreport.txt"
echo "cat $LPmacsProjectReportFile | $(ssh2bscsub tee $RPmacsProjectReportFile)"

LPmacsGpfsReportFile=$(findReportFile projectGpfsreport.txt "$Date" "$YearMonth" "$NextYearMonth")
if [ -n "$LPmacsGpfsReportFile" ]
then
    RPmacsGpfsReportFile="${RReportDir}/${Date}-projectGpfsreport.txt"
    echo "cat $LPmacsGpfsReportFile | $(ssh2bscsub tee $RPmacsGpfsReportFile)"

fi


