#!/bin/bash

. v${Version:=5}ArgHandler

bq query --use_legacy_sql=false --format=csv --allow_large_results --max_rows=1000000 --parameter="InvoiceMonth:STRING:${opt_y}${opt_m}" '

'"$(< v5TempFunctions)"'

DROP TABLE IF EXISTS
        `'"${Project}.${Dataset}"'.v5EstTotalStaticGearOverheadMetrics`
    ;

CREATE TABLE IF NOT EXISTS
        `'"${Project}.${Dataset}"'.v5EstTotalStaticGearOverheadMetrics`
    (
         InvoiceMonth				STRING

       , TotalOverheadComputeCosts		FLOAT64
       , TotalOverheadComputeCpuHours		FLOAT64

       , TotalOverheadComputeDynamicCpuHours	FLOAT64
       , TotalOverheadComputeDynamicCosts	FLOAT64

       , TotalOverheadComputeStaticCpuHours	FLOAT64
       , TotalOverheadComputeStaticCosts	FLOAT64

       , TotalOverheadComputeLabeledCosts	FLOAT64
       , TotalOverheadComputeUnLabeledCosts	FLOAT64

       , TotalOverheadStorageCosts		FLOAT64
       , TotalOverheadStorageStandardCosts	FLOAT64
       , TotalOverheadStorageStandardGb		FLOAT64
       , TotalOverheadStorageColdlineCosts	FLOAT64
       , TotalOverheadStorageColdlineGb		FLOAT64
       , TotalOverheadStorageArchiveCosts	FLOAT64
       , TotalOverheadStorageArchiveGb		FLOAT64

       , TotalOverheadMiscCosts			FLOAT64

       , EstGcpTotalStaticGearCpuHours		FLOAT64
       , EstGcpTotalStaticGearCosts		FLOAT64

       , EstGcpTotalOverheadCpuHours		FLOAT64
       , EstGcpTotalOverheadCosts		FLOAT64
    );

DELETE FROM 
        `'"${Project}.${Dataset}"'.v5EstTotalStaticGearOverheadMetrics`
    WHERE
        InvoiceMonth = @InvoiceMonth
    ;

INSERT
    `'"${Project}.${Dataset}"'.v5EstTotalStaticGearOverheadMetrics`
    SELECT
         t1.InvoiceMonth

       , TotalOverheadComputeCosts
       , TotalOverheadComputeCpuHours

       , TotalOverheadComputeDynamicCpuHours
       , TotalOverheadComputeDynamicCosts

       , TotalOverheadComputeStaticCpuHours
       , TotalOverheadComputeStaticCosts

       , TotalOverheadComputeLabeledCosts
       , TotalOverheadComputeUnLabeledCosts

       , TotalOverheadStorageCosts
       , TotalOverheadStorageStandardCosts
       , TotalOverheadStorageStandardGb
       , TotalOverheadStorageColdlineCosts
       , TotalOverheadStorageColdlineGb
       , TotalOverheadStorageArchiveCosts
       , TotalOverheadStorageArchiveGb

       , TotalOverheadMiscCosts

       , EstGcpTotalStaticGearCpuHours
       , EstGcpTotalStaticGearCosts

       , EstGcpTotalOverheadCpuHours
       , EstGcpTotalOverheadCosts

    FROM (
        SELECT 
                InvoiceMonth
    
              , SUM(AllocatedGcpGearComputeCosts) AS TotalOverheadComputeCosts
              , SUM(AllocatedGcpGearComputeCpuHours) AS TotalOverheadComputeCpuHours
              , SUM(AllocatedGcpGearComputeDynamicCpuHours) AS TotalOverheadComputeDynamicCpuHours
              , SUM(AllocatedGcpGearComputeDynamicCosts) AS TotalOverheadComputeDynamicCosts
            
              , SUM(AllocatedGcpGearComputeStaticCpuHours) AS TotalOverheadComputeStaticCpuHours
              , SUM(AllocatedGcpGearComputeStaticCosts) AS TotalOverheadComputeStaticCosts
            
              , SUM(AllocatedGcpGearComputeLabeledCosts) AS TotalOverheadComputeLabeledCosts
              , SUM(AllocatedGcpGearComputeUnLabeledCosts) AS TotalOverheadComputeUnLabeledCosts
              , SUM(AllocatedGcpGearStorageCosts) AS TotalOverheadStorageCosts
              , SUM(AllocatedGcpGearStorageStandardCosts) AS TotalOverheadStorageStandardCosts
              , SUM(AllocatedGcpGearStorageStandardGb) AS TotalOverheadStorageStandardGb
              , SUM(AllocatedGcpGearStorageColdlineCosts) AS TotalOverheadStorageColdlineCosts
              , SUM(AllocatedGcpGearStorageColdlineGb) AS TotalOverheadStorageColdlineGb
              , SUM(AllocatedGcpGearStorageArchiveCosts) AS TotalOverheadStorageArchiveCosts
              , SUM(AllocatedGcpGearStorageArchiveGb) AS TotalOverheadStorageArchiveGb
           
              , SUM(AllocatedGcpGearMiscCosts) AS TotalOverheadMiscCosts
            
          FROM
              `'"${Project}.${Dataset}"'.v5AllocatedGcpFwGroupProjectGears`
          WHERE
                 InvoiceMonth = @InvoiceMonth
    	     AND ( FwGroup IS NULL OR FwGroup = "flywheel-static" )
          GROUP BY
    	     InvoiceMonth
     ) t1
     LEFT JOIN (
        SELECT
	      InvoiceMonth
	    , EstGcpTotalStaticGearCpuHours
            , GcpTotalComputeStaticCosts * (EstGcpTotalStaticGearCpuHours / GcpTotalComputeStaticCpuHours) AS EstGcpTotalStaticGearCosts

	    , (GcpTotalComputeStaticCpuHours - EstGcpTotalStaticGearCpuHours) AS EstGcpTotalOverheadCpuHours
	, GcpTotalComputeStaticCosts * (GcpTotalComputeStaticCpuHours - EstGcpTotalStaticGearCpuHours) / GcpTotalComputeStaticCpuHours AS EstGcpTotalOverheadCosts
        FROM (
           SELECT
	         InvoiceMonth
	       , FwTotalDynamicCpuHours
	       , GcpTotalComputeDynamicCpuHours
	       , GcpTotalComputeStaticCosts
	       , GcpTotalComputeStaticCpuHours
               , FwTotalStaticCpuHours * prorate(GcpTotalComputeDynamicCpuHours, FwTotalDynamicCpuHours) AS EstGcpTotalStaticGearCpuHours
	   FROM
               `'"${Project}.${Dataset}"'.v5GcpFwTotalComputeStorageMetrics`
           WHERE
               InvoiceMonth = @InvoiceMonth

        )
    ) t2
    ON
	    t1.InvoiceMonth = t2.InvoiceMonth
    ;

' | OutputControl $opt_v

bq query --use_legacy_sql=false --format=csv --allow_large_results --max_rows=1000000 --parameter="InvoiceMonth:STRING:${opt_y}${opt_m}" '


SELECT 
          InvoiceMonth
	  
  , ROUND(TotalOverheadComputeCosts,2) AS TotalOverheadComputeCosts
  , ROUND(TotalOverheadComputeCpuHours,2) AS TotalOverheadComputeCpuHours
  , ROUND(TotalOverheadComputeDynamicCpuHours,2) AS TotalOverheadComputeDynamicCpuHours
  , ROUND(TotalOverheadComputeDynamicCosts,2) AS TotalOverheadComputeDynamicCosts

  , ROUND(TotalOverheadComputeStaticCpuHours,2) AS TotalOverheadComputeStaticCpuHours
  , ROUND(TotalOverheadComputeStaticCosts,2) AS TotalOverheadComputeStaticCosts

  , ROUND(TotalOverheadComputeLabeledCosts,2) AS TotalOverheadComputeLabeledCosts
  , ROUND(TotalOverheadComputeUnLabeledCosts,2) AS TotalOverheadComputeUnLabeledCosts
  , ROUND(TotalOverheadStorageCosts,2) AS TotalOverheadStorageCosts
  , ROUND(TotalOverheadStorageStandardCosts,2) AS TotalOverheadStorageStandardCosts
  , ROUND(TotalOverheadStorageStandardGb,2) AS TotalOverheadStorageStandardGb
  , ROUND(TotalOverheadStorageColdlineCosts,2) AS TotalOverheadStorageColdlineCosts
  , ROUND(TotalOverheadStorageColdlineGb,2) AS TotalOverheadStorageColdlineGb
  , ROUND(TotalOverheadStorageArchiveCosts,2) AS TotalOverheadStorageArchiveCosts
  , ROUND(TotalOverheadStorageArchiveGb,2) AS TotalOverheadStorageArchiveGb

  , ROUND(TotalOverheadMiscCosts,2) AS TotalOverheadMiscCosts

	, ROUND(EstGcpTotalStaticGearCpuHours, 2) AS EstGcpTotalStaticGearCpuHours
	, ROUND(EstGcpTotalStaticGearCosts, 2) AS EstGcpTotalStaticGearCost

	, ROUND(EstGcpTotalOverheadCpuHours, 2) AS EstGcpTotalOverheadCpuHours
	, ROUND(EstGcpTotalOverheadCosts, 2) AS EstGcpTotalOverheadCost

  FROM
             `'"${Project}.${Dataset}"'.v5EstTotalStaticGearOverheadMetrics` 

  ;


' | OutputControl column
